name: NostalProtect
version: '${project.version}'
main: dev.nostal.nostalprotect.NostalProtect
api-version: 1.19
authors: [ Meffu ]
description: Protect your world with easy to use permissions
commands:
  nostalprotect:
    description: Display the help command of NostalProtect.
    usage: /<command>
    aliases: [np]
  npdebug:
    description: Toggle the debug mode of NostalProtect.
    usage: /<command>